### ISSUE TITLE
Customize the font overridden name

### ISSUE THREAD

**Issue by edimitchel** [unjs/fontaine#19]
### 🆒 Your use case

Probably in some case, we won't have that override name in the font name.

### 🆕 The solution you'd like

I would like to suggest to customize the overridden name.

### 🔍 Alternatives you've considered

I probably not understand well, so let me know if I'm wrong.

**Comment by danielroe** [comment]
It _shouldn't_ matter what the override name is, as long as it matches between the font-face rule and the font-family.

But it should be possible to customise it.

**Comment by danielroe** [comment]
Are you experiencing an issue?

**Comment by edimitchel** [comment]
no but as I'm a bit perfectionist, this could be an issue for me :p
